// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.30;

import {Test} from "forge-std/Test.sol";
import {RewardsDistributor} from "../src/RewardsDistributor.sol";
import {MockERC20} from "./mocks/MockERC20.sol";

/// @notice Proves the TypeScript tree builder and the Solidity verifier agree.
///
/// @dev `@ponswars/rewards-math` builds the tree that goes on chain, and
/// `RewardsDistributor` decides whether a proof from it is valid. Nothing in
/// either codebase forces them to share a convention — the leaf encoding, the
/// double hash, the sorted pairing and the promotion of an odd node are four
/// separate places they could quietly diverge.
///
/// If they diverge one of two things happens, and both are severe: a whole
/// distribution becomes unclaimable, or a proof the contract accepts pays out
/// SPY that was never allocated.
///
/// So the fixture is generated by the real TypeScript builder and consumed here
/// by the real contract. `scripts/generate-merkle-fixture.mjs --check` runs in
/// the verify gate, so the fixture cannot go stale without the build failing.
contract MerkleConformanceTest is Test {
    RewardsDistributor internal distributor;
    MockERC20 internal spy;

    address internal admin = makeAddr("admin");
    address internal publisher = makeAddr("publisher");

    string internal fixture;
    uint256 internal distributionId;
    bytes32 internal root;
    uint256 internal total;
    uint256 internal claimCount;

    function setUp() public {
        fixture = vm.readFile("contracts/test/fixtures/merkle.json");

        distributionId = vm.parseJsonUint(fixture, ".distributionId");
        root = vm.parseJsonBytes32(fixture, ".root");
        total = vm.parseJsonUint(fixture, ".total");
        claimCount = vm.parseJsonUint(fixture, ".claimCount");

        spy = new MockERC20("Stock Token", "SPY", 6);
        distributor = new RewardsDistributor(spy, admin);

        // Read the role before pranking. vm.prank applies to the next call, and
        // DISTRIBUTION_PUBLISHER_ROLE() is itself a call - it would consume the
        // prank and leave grantRole running as this contract.
        bytes32 publisherRole = distributor.DISTRIBUTION_PUBLISHER_ROLE();
        vm.prank(admin);
        distributor.grantRole(publisherRole, publisher);

        spy.mint(address(distributor), total);

        vm.prank(publisher);
        distributor.publishDistribution(distributionId, root, total);
    }

    function _path(uint256 index, string memory field) internal pure returns (string memory) {
        return string.concat(".claims[", vm.toString(index), "].", field);
    }

    function test_fixtureIsWellFormed() public view {
        assertGt(claimCount, 0, "fixture has no claims");
        assertTrue(root != bytes32(0), "fixture root is empty");

        // An odd count is what makes this fixture worth having: it exercises the
        // promoted-node path that an even tree never reaches.
        assertEq(claimCount % 2, 1, "fixture should hold an odd number of claims");
    }

    function test_everyTypeScriptProofVerifiesOnChain() public {
        uint256 paid = 0;

        for (uint256 i = 0; i < claimCount; i++) {
            address account = vm.parseJsonAddress(fixture, _path(i, "wallet"));
            uint256 amount = vm.parseJsonUint(fixture, _path(i, "amount"));
            bytes32[] memory proof = vm.parseJsonBytes32Array(fixture, _path(i, "proof"));

            // forge-lint: disable-next-line(calls-loop)
            distributor.claim(distributionId, account, amount, proof);

            assertEq(spy.balanceOf(account), amount, "claimant was not paid the allocation");
            paid += amount;
        }

        assertEq(paid, total, "claims did not settle the published total");
        assertEq(distributor.outstandingCommitment(), 0, "commitment outstanding after all claims");
        assertEq(spy.balanceOf(address(distributor)), 0, "SPY left in the distributor");
    }

    function test_leafEncodingMatches() public view {
        // The leaf the TypeScript builder recorded must be the leaf the contract
        // reconstructs from the same three fields. This is the single most
        // likely place for the two to diverge, because the encoding is written
        // twice — once in viem, once in Solidity.
        for (uint256 i = 0; i < claimCount; i++) {
            address account = vm.parseJsonAddress(fixture, _path(i, "wallet"));
            uint256 amount = vm.parseJsonUint(fixture, _path(i, "amount"));
            bytes32 recorded = vm.parseJsonBytes32(fixture, _path(i, "leaf"));

            bytes32 rebuilt =
                keccak256(bytes.concat(keccak256(abi.encode(distributionId, account, amount))));
            assertEq(rebuilt, recorded, "leaf encoding differs between TypeScript and Solidity");
        }
    }

    function test_aTamperedAmountIsRejected() public {
        // Confirms the fixture proves something: a proof that verifies for the
        // real amount must fail for any other, or the test above would pass even
        // with a broken verifier.
        address account = vm.parseJsonAddress(fixture, _path(0, "wallet"));
        uint256 amount = vm.parseJsonUint(fixture, _path(0, "amount"));
        bytes32[] memory proof = vm.parseJsonBytes32Array(fixture, _path(0, "proof"));

        vm.expectRevert(RewardsDistributor.InvalidProof.selector);
        distributor.claim(distributionId, account, amount + 1, proof);
    }

    function test_anotherAccountsProofIsRejected() public {
        address first = vm.parseJsonAddress(fixture, _path(0, "wallet"));
        uint256 secondAmount = vm.parseJsonUint(fixture, _path(1, "amount"));
        bytes32[] memory firstProof = vm.parseJsonBytes32Array(fixture, _path(0, "proof"));

        vm.expectRevert(RewardsDistributor.InvalidProof.selector);
        distributor.claim(distributionId, first, secondAmount, firstProof);
    }
}
